### ISSUE TITLE
Inspector: Game history pagination failing

### ISSUE THREAD

**Issue by Slanman3755** [mtgatracker/mtgatracker#461] opened 2018-12-06 07:00 UTC
Every page of game history is the same as the first page in my inspector.  Restarting the game does not help.

**Comment by shawkinsl** [comment] 2018-12-06 16:56
Thanks for the report. Closing this as duplicate of #458. This was fixed in #455, but has not yet been released

**Closed by shawkinsl** 2018-12-06 16:56 UTC

**Comment by shawkinsl** [comment] 2018-12-06 17:00
I just released 5.0.3 as a pre-production release with the fix for this issue, check it out on the releases page.

**Comment by Slanman3755** [comment] 2018-12-06 18:05
Sorry I didnt search closed issues! :p
